services:
  postgres:
    image: postgres:15.6-alpine3.18
    restart: unless-stopped
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -q -U postgres -d airflow_meta_db && pg_isready -q -U postgres -d hive_meta_db
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - metastore_db:/var/lib/postgresql/data
      - ./containers/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  airflow:
    build:
      context: ./containers/airflow
    container_name: airflow
    depends_on:
      postgres:
        condition: service_healthy
    env_file: ./containers/airflow/airflow.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./jobs:/jobs
      - ./packages:/packages
      - ./containers/airflow/webserver_config.py:/opt/airflow/webserver_config.py
        # for disabling authentication for faster iterations
    ports:
      - 8080:8080

  # HDFS: https://github.com/big-data-europe/docker-hadoop/blob/master/docker-compose-v3.yml
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    container_name: namenode
    restart: unless-stopped
    ports:
      - 9870:9870
    volumes:
      - namenode:/hadoop/dfs/name
    env_file:
      - ./containers/hadoop/hadoop.env
    environment:
      - CLUSTER_NAME=test

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode
    container_name: datanode
    restart: unless-stopped
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./containers/hadoop/hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"

  # Hive
  hive-metastore:
    image: apache/hive:3.1.3
    hostname: hive-metastore
    container_name: hive-metastore
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - HIVE_CUSTOM_CONF_DIR=/hive-custom-conf
      - DB_DRIVER=postgres
      - SERVICE_NAME=metastore
      - IS_RESUME=true
    volumes:
      - ./containers/hive-metastore/hive-site.xml:/hive-custom-conf/hive-site.xml
      - ./containers/hive-metastore/postgresql-42.7.2.jar:/opt/hive/lib/postgres.jar

  # Spark: https://hub.docker.com/r/bitnami/spark/
  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    env_file: ./containers/spark/spark-master.env
    volumes:
      - ./containers/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./packages:/packages
    ports:
      - 8081:8080

  spark-worker:
    image: bitnami/spark:3.5
    container_name: spark-worker
    env_file: ./containers/spark/spark-worker.env
    volumes:
      - ./containers/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./packages:/packages

volumes:
  metastore_db:
  namenode:
  datanode: